version: "3.1"

services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db_data:
