version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SecretPass@123
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    